---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: barbican-exporter
  namespace: openstack
  labels:
    app.kubernetes.io/name: barbican-exporter
    app.kubernetes.io/instance: barbican-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: barbican-exporter
      app.kubernetes.io/instance: barbican-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: barbican-exporter
        app.kubernetes.io/instance: barbican-exporter
    spec:
      nodeSelector:
        openstack-control-plane: enabled
      containers:
        - name: barbican-exporter
          image: quay.io/rackspace/barbican-exporter:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: BARBICAN_API_URL
              value: "http://barbican-api.openstack.svc.cluster.local:9311"
          ports:
            - name: metrics
              containerPort: 9100
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi

