---
# Helm overrides for Barbican Prometheus exporter
image:
  repository: quay.io/rackspace/barbican-exporter
  tag: latest
  pullPolicy: IfNotPresent
serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  namespace: prometheus
  labels: {}
nodeSelector:
  openstack-control-plane: enabled
env:
  - name: BARBICAN_API_URL
    value: "http://barbican-api.openstack.svc.cluster.local:9311"
